version: "3.8"

services:
  jekyll:
    image: jekyll/jekyll:4 # Chirpy supporte Jekyll 4+
    command: jekyll serve --watch --force_polling --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle
    environment:
      JEKYLL_ENV: development
    stdin_open: true
    tty: true

volumes:
  bundle:
